[features]
seeds = false
skip-lint = false
idl = true

[programs.devnet]
compressed_nft = "FC5Qxs25hfb7zGXUvr5tWn5mMz6Wp2hDnY1gATJGz2wE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./.local_keys/payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
